[package]
name = "gerac"
authors = ["TypeSafeSchwalbe"]
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.51"
features = [
    "Win32_Foundation",
    "Win32_System_Console"
]

[dependencies]
json = "0.12.4"