[package]
name = "gerac"
authors = ["TypeSafeSchwalbe"]
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.51"
features = [
    "Win32_Foundation",
    "Win32_System_Console"
]

[dependencies]
